export const FETCH_PLAYER_ID_REQUEST = 'FETCH_PLAYER_ID_REQUEST'
export const FETCH_PLAYER_ID_SUCCESS = 'FETCH_PLAYER_ID_SUCCESS'

export const FETCH_PLAYER_STATS_REQUEST = 'FETCH_PLAYER_STATS_REQUEST'
export const FETCH_PLAYER_STATS_SUCCESS = 'FETCH_PLAYER_STATS_SUCCESS'

export const FETCH_PLAYER_NAME_YEAR = 'FETCH_PLAYER_NAME_YEAR'

export const HIDE_RESULTS = 'HIDE_RESULTS'
export const HIDE_RESULTS_COMP = 'HIDE_RESULTS_COMP'
export const SHOW_INPUT_ERROR = 'SHOW_INPUT_ERROR'
